# base URLs for services
# should end in '/'
default: &default
    fcrepo:
        fcrepo_url: <%= ENV['FCREPO_URL'] %>
        solr_url: <%= ENV['SOLR_URL'] %>
        image_url: <%= ENV['IIIF_IMAGE_URL'] %>
        manifest_url: <%= ENV['IIIF_MANIFEST_URL'] %>
    fedora2:
        fedora2_url: <%= ENV['FEDORA2_URL'] %>
        solr_url: <%= ENV['FEDORA2_SOLR_URL'] %>
        fcrepo_solr_url: <%= ENV['FCREPO_SOLR_URL'] %>
        image_url: <%= ENV['IIIF_IMAGE_URL'] %>
        manifest_url: <%= ENV['IIIF_MANIFEST_URL'] %>
development:
    <<: *default
test:
    <<: *default
production:
    <<: *default
