# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a5d164bc9dbb6a80c6382d42fac2f8fc748a4dbd6f6d4b6a9eccaf111a9184988ce3f31cf045a7442fe0db58ae970e98a983549b2dd661dde5cb07cb9967297

test:
  secret_key_base: 1c33445aaa0f0c9b1a1ac0997b0f05c7db8adf1adaa6f431def066144a5e7b537e65105e9b5be80cbfaf1ac4cf6d7fc015bd92704e530e2700a8383a6916c27a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
